#!/usr/bin/env bash
source common.sh
source debian.sh
source $CODE/dotfiles/link.sh

set -o xtrace

sudo apt-get update
sudo apt-get dist-upgrade
sudo apt-get autoremove

INSTALL=$(cat $HOME/.install.apt | grep -v "^$" | grep -v "^#" | tr "\n" " ")
install_packages ${INSTALL[@]}

REMOVE=$(cat $HOME/.remove.apt | grep -v "^$" | grep -v "^#" | tr "\n" " ")
remove_packages ${REMOVE[@]}

# for K in "${!GCONF[@]}"
# do
#     gconftool-2 --type=string --set $K "${GCONF[$K]}"
# done

# for K in "${!GSETTINGS[@]}"
# do
#     gsettings set $K "${GSETTINGS[$K]}"
# done
