#!/usr/bin/env bash

EMACSCLIENT="/usr/bin/emacsclient"
EMACS="emacs"
NCUT="9"
if [[ $(uname) == 'Darwin' ]]; then
    EMACSCLIENT="/usr/local/bin/emacsclient"
    EMACS="Emacs"
    NCUT="8"
fi

SOCKET_FILE=$(lsof -c "$EMACS" | grep server | tr -s " " | head -1 | cut -d' ' -f$NCUT | tr -d '\n')
"$EMACSCLIENT" --tty "$@" --socket-name="$SOCKET_FILE"
