#!/usr/bin/env bash
source common.sh
source debian.sh

_PWD=$(pwd)
section "Hey Trevor! New Debian install huh? Hope nothing broke!" "="

section "Installing nvidia drivers"
install_packages build-essential nvidia-driver nvidia-xconfig nvidia-settings
echo "--- Generating xorg.conf"
sudo nvidia-xconfig
sudo rm -f /etc/X11/xorg.conf.*

if ! package_installed "google-chrome-beta"; then
    section "Installing Google Chrome"
    CHROME=google-chrome-beta_current_amd64.deb
    echo "--- Downloading $CHROME"
    wget -O /tmp/chrome.deb https://dl.google.com/linux/direct/$CHROME
    echo "--- Installing Chrome"
    sudo gdebi /tmp/chrome.deb
    if [[ $? == 0 ]]
    then
        "--- Chrome installed"
    else
        echo "--- Error installing Chrome"
    fi
    rm -f /tmp/chrome.deb
fi

section "Setting up zsh"
install_packages zsh
if [[ $(grep "$USER" /etc/passwd) != */bin/zsh ]]; then
    echo "--- Setting zsh as $USER's shell"
    chsh -s /bin/zsh
fi
if [[ ! -d $CODE/prezto ]]; then
    echo "--- Getting prezto"
    git clone --recursive -b tbekolay https://github.com/tbekolay/prezto.git "$CODE/prezto"
fi
checkandlink "$CODE/prezto" "$HOME/.zprezto"
for ZFILE in zlogin zlogout zpreztorc zprofile zshenv zshrc; do
    SRC="$CODE/prezto/runcoms/$ZFILE"
    DST="$HOME/.$ZFILE"
    checkandlink "$SRC" "$DST"
done

section "Setting up emacs"
install_packages emacs
if [[ ! -d $CODE/prelude ]]; then
    echo "--- Getting prelude"
    git clone -b tbekolay https://github.com/tbekolay/prelude.git "$CODE/prelude"
fi
checkandlink "$CODE/prelude" "$HOME/.emacs.d"

if [[ ! -d $CODE/dotfiles ]]; then
    section "Setting up dotfiles"
    git clone https://github.com/tbekolay/dotfiles.git "$CODE/dotfiles"
fi
