#!/usr/bin/env bash
cd $HOME
if [[ -e "/tmp/rtorrent.session" ]]; then
    echo "rtorrent already started. Attaching to session."
else
    echo "Starting rtorrent."
fi
echo "  C-\\ : Detach"
echo "  C-q : Quit"
echo "  Backspace : Add (file or URL)"
echo "  C-s : Start"
echo "  C-d : Stop; remove"
read -p "Press [Enter] to continue."
dtach -A /tmp/rtorrent.session rtorrent
